// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3MtJwS0hkFiM09yWNJvtEwcPkv8HuI_U',
    appId: '1:50400098569:web:b9fbe6a73c0c0d5cfcfbd8',
    messagingSenderId: '50400098569',
    projectId: 'themuro',
    authDomain: 'themuro.firebaseapp.com',
    storageBucket: 'themuro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByburYWATmjMjgECG80mKcOwwpaKMZ8oo',
    appId: '1:50400098569:android:f9b715138b98eb65fcfbd8',
    messagingSenderId: '50400098569',
    projectId: 'themuro',
    storageBucket: 'themuro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpI-17dtGAUSr5cOkfSwDFx8gGPYIHX44',
    appId: '1:50400098569:ios:80750d13daa31130fcfbd8',
    messagingSenderId: '50400098569',
    projectId: 'themuro',
    storageBucket: 'themuro.appspot.com',
    iosClientId: '50400098569-a0kte329e1a91muj5uqo3b4rss79jgnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpI-17dtGAUSr5cOkfSwDFx8gGPYIHX44',
    appId: '1:50400098569:ios:5ee0b2f0ae50c2e2fcfbd8',
    messagingSenderId: '50400098569',
    projectId: 'themuro',
    storageBucket: 'themuro.appspot.com',
    iosClientId: '50400098569-jbps5gd1mojuv6s91fssmgmgqk8dag0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.redApp.RunnerTests',
  );
}
